# 아래 client-id와 client-secret은 예시로 넣은 더미데이터입니다. 참고만 부탁드려요.

spring:
  profiles: local
  jpa:
    database: mysql
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?useSSL=false&serverTimezone=UTC
    username: root
    password: example
    driver-class-name: com.mysql.cj.jdbc.Driver
#  h2:
#    console:
#      enabled: true
#      path: /console
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: {google-client-id}
            client-secret: {google-client-secret}
          facebook:
            client-id: {facebook-client-id}
            client-secret: {facebook-client-secret}
custom:
  oauth2:
    kakao:
      client-id: {kakao-client-id}
      client-secret: {kakao-client-secret}
    naver:
      client-id: {naver-client-id}
      client-secret: {naver-client-secret}
